added redis to Dockerfile

diff --git a/config/Dockerfile b/config/Dockerfile
--- a/config/Dockerfile
+++ b/config/Dockerfile
@@ -2,6 +2,16 @@ FROM wordpress:php8.2-fpm-alpine
 
 RUN apk add --no-cache mysql-client bash unzip
 
+RUN set -xe; \
+  apk --no-cache update && apk --no-cache upgrade \
+  && apk add --no-cache --virtual .build-deps ${PHPIZE_DEPS} \
+  && pecl install redis \
+  && docker-php-ext-enable redis  \
+  && apk add --no-cache libc6-compat openssl1.1-compat \
+  # Cleanup build deps
+  && apk del .build-deps \
+  && rm -rf /tmp/* /var/cache/apk/*
+
 RUN docker-php-ext-install pdo pdo_mysql
 
 RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
